name: Run go-ethereum unit tests

on:
  workflow_dispatch:
    inputs:
      tfhe_rs_ref:
        description: "Branch, tag or commit SHA1 to checkout TFHE-rs"
        required: true
        default: "main"
        type: string
      tfhe_cli_ref:
        description: "Branch, tag or commit SHA1 to checkout TFHE-cli"
        required: true
        default: "main"
        type: string

jobs:
  build_and_test:
    name: Build and test go-ethereum
    runs-on: ubuntu-latest
    steps:
      - name: Check out tfhe-rs
        uses: actions/checkout@v3
        with:
          repository: zama-ai/tfhe-rs
          ref: ${{ inputs.tfhe_rs_ref }}
          path: tfhe-rs

      - name: Check out tfhe-cli
        uses: actions/checkout@v3
        with:
          repository: tremblaythibaultl/tfhe-cli
          ref: ${{ inputs.tfhe_cli_ref }}
          path: tfhe-cli

      - name: Check out go-ethereum
        uses: actions/checkout@v3
        with:
          path: go-ethereum

      - name: Build C API
        working-directory: ./tfhe-rs
        run: make build_c_api

      - name: Move library files
        run: |
          mv ./tfhe-rs/target/release/tfhe.h ./go-ethereum/core/vm/
          sudo mv ./tfhe-rs/target/release/libtfhe.* /usr/lib/

      - name: Generate TFHE-rs keys
        working-directory: ./tfhe-cli
        run: cargo run --release keygen bin .

      - name: Move keys
        run: |
          mkdir -p $HOME/.evmosd/zama/keys/network-fhe-keys
          mv ./tfhe-cli/client_key.bin $HOME/.evmosd/zama/keys/network-fhe-keys/cks
          mv ./tfhe-cli/server_key.bin $HOME/.evmosd/zama/keys/network-fhe-keys/sks

      - name: Run tests
        working-directory: ./go-ethereum/core/vm
        run: go test -v
