name: Run go-ethereum unit tests

on:
  push:
    branches: [ "1.10.19-zama" ]
  pull_request:
    branches: [ "1.10.19-zama" ]

jobs:
  build_and_test:
    name: Build and test go-ethereum
    runs-on: ubuntu-latest
    steps:
      - name: Check out tfhe-rs
        uses: actions/checkout@v3
        with:
          repository: zama-ai/tfhe-rs
          ref: 0.2.1
          path: tfhe-rs

      - name: Check out tfhe-cli
        uses: actions/checkout@v3
        with:
          repository: tremblaythibaultl/tfhe-cli
          ref: main
          path: tfhe-cli

      - name: Check out go-ethereum
        uses: actions/checkout@v3
        with:
          path: go-ethereum

      - name: Build C API
        working-directory: ./tfhe-rs
        run: make build_c_api

      - name: Move library files
        run: |
          mv ./tfhe-rs/target/release/tfhe.h ./go-ethereum/core/vm/
          sudo mv ./tfhe-rs/target/release/libtfhe.* /usr/lib/

      - name: Generate TFHE-rs keys
        working-directory: ./tfhe-cli
        run: cargo run --release keygen bin .

      - name: Move keys
        run: |
          mkdir -p $HOME/.evmosd/zama/keys/network-fhe-keys
          mv ./tfhe-cli/client_key.bin $HOME/.evmosd/zama/keys/network-fhe-keys/cks
          mv ./tfhe-cli/server_key.bin $HOME/.evmosd/zama/keys/network-fhe-keys/sks

      - name: Run tests
        working-directory: ./go-ethereum/core/vm
        run: go test -v
