name: Run go-ethereum unit tests

on:
  push:
    branches: [ "1.10.19-zama" ]
  pull_request:
    branches: [ "1.10.19-zama" ]

jobs:
  build_and_test:
    name: Build and test go-ethereum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TFHE-rs
        uses: actions/checkout@v3
        with:
          repository: zama-ai/tfhe-rs
          ref: 189f02b696acad96ac18e6549714d64e4031a795
          path: tfhe-rs

      - name: Checkout zbc-fhe-tool
        uses: actions/checkout@v3
        with:
          repository: zama-ai/zbc-fhe-tool
          ref: main
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          path: zbc-fhe-tool

      - name: Checkout go-ethereum
        uses: actions/checkout@v3
        with:
          path: go-ethereum

      - name: Build C API
        working-directory: ./tfhe-rs
        run: make build_c_api

      - name: Move library files
        run: |
          sudo mv ./tfhe-rs/target/release/tfhe.h /usr/include
          sudo mv ./tfhe-rs/target/release/libtfhe.so /usr/lib/

      - name: Generate TFHE-rs keys
        working-directory: ./zbc-fhe-tool
        run: |
          mkdir -p $HOME/.evmosd/zama/keys/network-fhe-keys
          cargo run --features tfhe/x86_64-unix --release -- generate-keys $HOME/.evmosd/zama/keys/network-fhe-keys

      - name: Run tests
        working-directory: ./go-ethereum/core/vm
        run: go test -v
